apiVersion: v2
name: external-dns
description: A wrapper Helm chart for external-dns
type: application
version: 0.0.0
dependencies:
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.18.0
